openapi: 3.0.2
info:
  title: User Roles
  description: Roles associated with users
  version: 1.0.0
servers:
  - url: /api/v1
paths:
  /roles:
    get:
      description: Get available roles.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  roles:
                    type: array
                    items:
                      $ref: "#/components/schemas/roleDto"

components:
  schemas:
    roleDto:
      example:
        id: 47cf9d88-aa5c-4e88-9aa5-1bb26763c92d
        name: Admin
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
    error:
      type: object
      properties:
        message:
          type: string